name: padron-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - beautifulsoup4
  - lxml
  - pandas
  - requests
  - pikepdf
  - pymupdf
  - duckdb
  - openpyxl
  - jellyfish
  - splink
  - altair
